### PR TITLE
Fix list commands

### LINKED ISSUE #151: List only displays students
List should display both students and courses

### LINKED ISSUE #154: view_course should be more accurately named view_courses

### PR DESCRIPTION
**Pull request by gnahuy123**
List now displays courses and students
Renamed view_course to view_courses

Closes #154 
Closes #151

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ListCommand.java [hunk 1]
```diff
@@ -12,13 +13,14 @@ public class ListCommand extends Command {
...
 
-    public static final String MESSAGE_SUCCESS = "Listed all persons";
+    public static final String MESSAGE_SUCCESS = "Listed all persons and courses";
 
 
     @Override
     public CommandResult execute(Model model) {
         requireNonNull(model);
         model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
+        model.updateFilteredCourseList(PREDICATE_SHOW_ALL_COURSES);
```
Comment (siuuuuuuuuuuuuuuuuuu) [inline src/main/java/seedu/address/logic/commands/ListCommand.java]: lgtm! good idea to make list show all students AND courses instead of just students as the scope of the list command also includes courses

File: src/main/java/seedu/address/logic/commands/ViewCourseCommand.java [hunk 2]
```diff
@@ -10,7 +10,7 @@
  */
 public class ViewCourseCommand extends Command {
 
-    public static final String COMMAND_WORD = "view_course";
+    public static final String COMMAND_WORD = "view_courses";
```
Comment (siuuuuuuuuuuuuuuuuuu) [inline src/main/java/seedu/address/logic/commands/ViewCourseCommand.java]: good idea to edit the command name to be more intuitive and user-friendly!

**Review by siuuuuuuuuuuuuuuuuuu — COMMENTED** [review]
lgtm! good improvements for user experience!
