### PR TITLE
fix/delete-course

### LINKED ISSUE #139: DeleteCourse: Error is not raised
It should raise an error message instead of return a command result when
- student is not removed before deleting the course
- course id is not found.

### PR DESCRIPTION
**Pull request by desmondwong1215**
- raise error when
    - students are not removed before deleting the course
    - course id is not found
 - update relevant test cases
 - close #139

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteCourseCommand.java [hunk 1]
```diff
@@ -30,14 +32,14 @@ public DeleteCourseCommand(CourseId courseId) {
     }
 
     @Override
-    public CommandResult execute(Model model) {
+    public CommandResult execute(Model model) throws CommandException {
         assert model != null : "Model cannot be null";
         Course course = model.getCourseById(courseId);
         if (course == null) {
-            return new CommandResult(MESSAGE_NOT_FOUND);
+            throw new CommandException(String.format(MESSAGE_NOT_FOUND, courseId));
```
Comment (Beastarz) [inline src/main/java/seedu/address/logic/commands/DeleteCourseCommand.java]: ensuring a command exception is thrown is important such that the user knows what is wrong
