### PR TITLE
Fix/edit student

### LINKED ISSUE #125: Success message of edit_student command indicates 'Student' as 'Person'
should be Edited Student instead of Edited Person

### LINKED ISSUE #137: EditStudentCommand: Unclear Error Message
When the teachers try to edit the student ID, it should show the error message that tells teachers that the student's ID cannot be changed.

### PR DESCRIPTION
**Pull request by desmondwong1215**
- Change 'Person' in the error message and the success message to 'Student'
- Show an error message that indicates the student ID should not be changed when teachers try to change it.
- Add test cases for the changes.
- close #137 , 
- close #125

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditStudentCommand.java [hunk 1]
```diff
@@ -29,8 +29,8 @@ public class EditStudentCommand extends Command {
 
     public static final String COMMAND_WORD = "edit_student";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Edits the details of the person identified "
-            + "by the index number used in the displayed person list. "
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Edits the details of the student identified "
```
Comment (Beastarz) [inline src/main/java/seedu/address/logic/commands/EditStudentCommand.java]: nice catch of wrong command word string

**Review by Beastarz — COMMENTED** [review]
lgtm
